version: "3.9"

services:
  web:
    build: .
    container_name: player_dashboard
    ports:
      - "8501:8501"
    environment:
      DB_HOST: faustinosapp.cjgwyy8iqgsn.us-east-2.rds.amazonaws.com
      DB_PORT: 3306
      DB_USER: faustinosapp
      DB_PASSWORD: faustinosapp
      DB_NAME: mysql
    volumes:
      - ./src:/app/src
    restart: unless-stopped